/* 

PROCEDURAL PROGRAMMING

1) 🚗 DIVIDED PROGRAM INFO SET OF FUNCTION. F()
2) 📟 DATA STORED IN BUNCH OF VARIABLES. 
3) 🙄 AS YOUR PROGRAM GROW YOU WILL FIND BUNCH OF FUCNTION, 
4) 😮 YOU WILL FINDS COPYING AND PASTING FUCNTION CODE AND ONE CHANGE IN ONE FUNCTION SEVERAL OTHER FUNCTION BREAKS.
5) 🥓 THIS IS WHAT ITS CALLED SPAGHETTI CODE.
6) 🛠 PP HAS FUNCTIONS WITH SO MANY PARAMETERS

*/

// EXAMPLE

let name = "John";
let designation = "Software Engineer";
let salary = 30000;

function getBio(name, designation, salary) {
  return name + designation + salary;
}

console.log(getBio());

// EVERYTHING HERE IS DECOUPLED, WE HAVE TO ASSUME OR FIND BY LOGIC THAT THESE 3 VARIABLES BELONGS TO getBio() FUNCTION
